name: CI

on:
  push: 
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs: 
    # This workflow contains a single job called build
    build:
      runs-on: ubuntu-latest    
      steps:
        # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
        - uses: actions/checkout@v2
        - name: Run a one-line script
          run: echo "Hello, World!"
        - name: Listing all files
          run: ls -al
        - name: Install npm and build webpack 
          run: |
            npm install
            npm run build
        
